nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  cpu:
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.0.cjs
